### ISSUE TITLE
How to pull in Lighthouse data in Google Data Studio?

### ISSUE THREAD

**Issue by ktiwari9** [JibbyJames/data-studio-lighthouse-gauge#16]
Hi James.

Thanks for the community visualization tool with lighthouse gauges. I am trying to build a report in Google Data studio which shows the site speeds picked up by lighthouse. For the website I am evaluating, these are the metrics I get in the lighthouse report:

![image](https://user-images.githubusercontent.com/5789469/155418594-0f9fdf9f-f46b-46ad-8702-36b78be3ebe1.png)

I'd like to be able to use and show this data in the the Google Data studio too. I managed to connect the gauge inside GDS but I am trying to figure out how do I get this data from Lighthouse? Any pointers?

I integrated Google Search Console as a data source which shows me these data points: 
![image](https://user-images.githubusercontent.com/5789469/155418809-a3b06988-a04c-4e41-94f3-e0bf650e6a8b.png)

But none of them are the actual page speeds I'd like for the gauge to show as Search Console doesn't have this data but Lighthouse does. I could use some help with this.

**Comment by JibbyJames** [comment]
Hi Kshitij,

Visualising lighthouse audit scores in Data Studio is why I first began to
create this community visualisation in the first place :)

You're basically going to need to require a solution that runs the tests,
and then outputs the results to a destination which you link Data Studio
with. There are several ways that you can go about this, but I'll describe
roughly how I went about it, but this isn't necessarily the best way to do
it.

At the very beginning, I used the Web Page Test API:
https://www.webpagetest.org/. This looks quite different from how I
remember it, but there are some guides there.

Then I found this Simo Ahava article about running the tests in Google
Cloud Platform:
https://www.simoahava.com/google-cloud/lighthouse-bigquery-google-cloud-platform/
.

This will introduce you to several components and libraries that will run
the lighthouse tests for you within a headless browser.

As his article points out though, this solution results in performance
metrics which aren't consistent, which is a very big flaw. To combat this I
just used the same node.js code, but executed it from within a Compute
Engine instance instead of a Cloud Function, that way the performance will
always be the same.

I can't go into too much more detail here, but the above should put you in
the right direction at least, if you chose to go the same route I did.
There may well be a better solution out there though.

Thanks,
James
